# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phaAction_text', models.CharField(max_length=200)),
                ('phaAction_resolution', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='phaitem',
            old_name='phaItem_text',
            new_name='phaItem_cause',
        ),
        migrations.AddField(
            model_name='phaitem',
            name='phaItem_consequence',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phaaction',
            name='phaItem',
            field=models.ManyToManyField(to='pha.PhaItem'),
        ),
    ]
