# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-05 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0002_auto_20170225_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phaaction',
            name='phaItem',
        ),
        migrations.AddField(
            model_name='phaitem',
            name='phaItem_action',
            field=models.ManyToManyField(to='pha.PhaAction'),
        ),
    ]
