# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0003_auto_20170305_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hierachy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='phaitem',
            name='phaItem_action',
            field=models.ManyToManyField(blank=True, to='pha.PhaAction'),
        ),
        migrations.AddField(
            model_name='hierachy',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pha.Type'),
        ),
    ]
