# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-08 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0005_auto_20170306_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pha.Hierachy')),
            ],
        ),
        migrations.CreateModel(
            name='phaStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Hiearchy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pha.Hierachy')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='phaitem',
            name='node',
        ),
        migrations.AddField(
            model_name='node',
            name='phaItems',
            field=models.ManyToManyField(blank=True, to='pha.PhaItem'),
        ),
        migrations.AddField(
            model_name='phastudy',
            name='nodes',
            field=models.ManyToManyField(to='pha.Node'),
        ),
        migrations.AddField(
            model_name='phastudy',
            name='particpants',
            field=models.ManyToManyField(blank=True, to='pha.Participant'),
        ),
    ]
